version: "2"
run:
  concurrency: 4
linters:
  default: none
  enable:
    - dupl
    - gochecknoinits
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    dupl:
      threshold: 100
    gocritic:
      disabled-checks:
        - wrapperFunc
        - hugeParam
      enabled-tags:
        - performance
        - style
        - experimental
    gocyclo:
      min-complexity: 15
    govet:
      enable-all: true
      disable:
        - fieldalignment
    misspell:
      locale: US

  exclusions:
    generated: lax
    rules:
      - linters:
          - staticcheck
        text: "at least one file in a package should have a package comment"
      - linters:
          - govet
        text: "composites: go.mongodb.org/mongo-driver/bson/primitive.E struct literal uses unkeyed fields"
      - linters:
          - revive
        text: "package-comments: should have a package comment"
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
