language: go

go:
  - "1.10.x"

go_import_path: github.com/go-pkgz/mongo

services: mongodb

before_install:
  - cp -rf .vendor vendor

before_script:
  - sleep 10

script:
  - MONGO_TEST=mongo go test -v ./...
